import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9ff",
        "secondary-fixed-dim": "#4ae183",
        "inverse-surface": "#203243",
        "on-secondary-fixed": "#00210c",
        "primary-fixed": "#b6ecf6",
        "secondary-container": "#6bfe9c",
        "surface-container-low": "#edf4ff",
        "on-tertiary-container": "#ffa867",
        "surface-container": "#e3efff",
        "on-error": "#ffffff",
        "primary": "#003b43",
        "tertiary-fixed-dim": "#ffb783",
        "secondary-fixed": "#6bfe9c",
        "surface-container-high": "#d9eaff",
        "on-tertiary-fixed-variant": "#713700",
        "outline": "#70797a",
        "outline-variant": "#c0c8ca",
        "surface": "#f7f9ff",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-lowest": "#ffffff",
        "on-background": "#091d2e",
        "on-secondary-fixed-variant": "#005228",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#40484a",
        "on-primary-fixed-variant": "#134e57",
        "surface-container-highest": "#d1e4fb",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-primary": "#9acfda",
        "tertiary-container": "#783b00",
        "surface-dim": "#c9dcf3",
        "tertiary": "#562900",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#9acfda",
        "on-tertiary-fixed": "#301400",
        "on-surface": "#091d2e",
        "on-secondary-container": "#00743a",
        "surface-variant": "#d1e4fb",
        "secondary": "#006d37",
        "on-primary-fixed": "#001f24",
        "on-primary-container": "#90c5cf",
        "background": "#f7f9ff",
        "error": "#ba1a1a",
        "primary-container": "#1a535c",
        "inverse-on-surface": "#e8f2ff",
        "surface-tint": "#30666f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap-sm": "8px",
        "section-margin": "32px",
        "card-padding": "16px",
        "stack-gap-md": "16px",
        "container-margin": "20px",
        "stack-gap-lg": "24px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "display-amount": ["Hanken Grotesk"],
        "label-caps": ["Work Sans"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Work Sans"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Work Sans"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-amount": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
};